export const SHOPPING_LIST = [
  {
    id: 1,
    category: "coffee",
    name: "아메리카노",
    value: 3000,
    imageUrl: "/week02/hw/assets/img/americano.jpg",
  },
  {
    id: 2,
    category: "coffee",
    name: "카페라떼",
    value: 3500,
    imageUrl: "/week02/hw/assets/img/latte.jpg",
  },
  {
    id: 3,
    category: "coffee",
    name: "카라멜 마끼아또",
    value: 3800,
    imageUrl: "/week02/hw/assets/img/macchiato.jpg",
  },
  {
    id: 4,
    category: "coffee",
    name: "연유라떼",
    value: 4000,
    imageUrl: "/week02/hw/assets/img/condensedmilk.jpg",
  },
  {
    id: 5,
    category: "beverage",
    name: "레몬에이드",
    value: 4000,
    imageUrl: "/week02/hw/assets/img/lemonade.png",
  },
  {
    id: 6,
    category: "beverage",
    name: "딸바스무디",
    value: 4500,
    imageUrl: "/week02/hw/assets/img/smoothie.png",
  },
  {
    id: 7,
    category: "beverage",
    name: "초콜릿라떼",
    value: 4000,
    imageUrl: "/week02/hw/assets/img/milkchocolate.png",
  },
  {
    id: 8,
    category: "beverage",
    name: "말차라떼",
    value: 4000,
    imageUrl: "/week02/hw/assets/img/matchalatte.png",
  },
  {
    id: 9,
    category: "dessert",
    name: "치즈케이크",
    value: 5000,
    imageUrl: "/week02/hw/assets/img/cheesecake.jpg",
  },
  {
    id: 10,
    category: "dessert",
    name: "피칸파이",
    value: 5000,
    imageUrl: "/week02/hw/assets/img/pecanpie.png",
  },
  {
    id: 11,
    category: "dessert",
    name: "롤케이크",
    value: 5500,
    imageUrl: "/week02/hw/assets/img/rollcake.png",
  },
  {
    id: 12,
    category: "dessert",
    name: "샌드위치",
    value: 6000,
    imageUrl: "/week02/hw/assets/img/sandwich.png",
  },
];
